### PR TITLE
Update Docker entrypoint for Update UDPC

### PR DESCRIPTION
**Pull request by Snuffy2**
# Breaking Changes
Updated the Docker Environment Variables to align with the JuicePass Proxy Arguments:
Old | New | 
-- | -- 
JUICEBOX_LOCAL_IP | `JUICEBOX_HOST`

Updated JuicePass Proxy Argument to use underscore consistently:
Old | New | 
-- | -- 
--juicebox-id | `--juicebox_id`

# Fixes/Enhancements

* Added `UPDATE_UDPC` and `JPP_HOST` Docker Variables
* Add `--jpp_host` as JuicePass Proxy argument for when `--src` isn't the same as the machine IP (like running in Docker bridge mode) and `--update_udpc` is true
* Python code formatting cleanup with black, isort, etc.

### CODE REVIEW

**Comment by snicker** [comment]
Ooops, sorry, I should have taken a look at this before setting the argument name to `juicepass_proxy_host`. You can probably revert changes to `README.md` and `juicepassproxy.py`

**Comment by snicker** [comment]
working on resolving the merge conflicts myself since I wasn't paying attention

**Review by snicker — APPROVED** [review]

**Comment by Snuffy2** [comment]
@snicker, sorry for the confusion. I should have been more clear. Anyway I just pushed out PRs #30 & #31 that should get the Docker container working again in the `edge` tag. We can monitor and see how it is running on our ends and how others who are also testing are reporting and hopefully this is ready for the 0.2.0 release later today/tomorrow.

**Comment by snicker** [comment]
thanks- should have tested before pushing those fixes quickly

**Pull request merged**
