### PR TITLE
implement some numbers to prepare to control charging current

### PR DESCRIPTION
**Pull request by ivanfmartinez**
Add some fields identified on #52 as number to be able to control charging parameters.

Before implementing the real control the proxy must be able to respond to the juicebox without enel x servers responding as #54 .

### CODE REVIEW

**Comment by snicker** [comment]
changing to draft while research continues in #39

**Comment by Snuffy2** [comment]
@ivanfmartinez I'm going to incorporate most of these changes into #58. As it is a large behind the scenes rewrite, it will likely be easier to put this code in the right new places as opposed to having you sort out the new places to put it later.

Of note, I may not incorporate `current_max_charging_callback` and `current_max_callback` yet, but I'll let you know for sure.

**Comment by ivanfmartinez** [comment]
> @ivanfmartinez I'm going to incorporate some of these changes into #58. As it is a large behind the scenes rewrite, it will likely be easier to put this code in the right new places as opposed to having you sort out the new places to put it later.
> 
> I'll clarify the full list here and in #58 of what I incorporated.

@Snuffy2 this callbacks are to be able to send new configuration values do the juicebox faster without waiting for a new message came from juicebox. But if you find another way to do this there is no problem.

**Comment by Snuffy2** [comment]
@ivanfmartinez ok if we close this PR?

**Comment by ivanfmartinez** [comment]
Now on #69

**Pull request closed without merging**
