### PR TITLE
Rewrite to async

### LINKED ISSUE #25: Transition from deprecated python telnetlib
Python telnetlib is deprecated in 3.11+ and removed from Python in 3.13. Will need to transition to another package for telnet at some point (not urgent). For now, the Dockerfile is fixed to Python 3.12.

Options could be:
* telnetlib3
* Exscript

### LINKED ISSUE #60: Add option for different local port
Requesting the addition of DEFAULT_SRC_PORT (or DEFAULT_LOCAL_PORT in possible upcoming async rewrite from @Snuffy2).

This would allow a different local port rather than the default 8047.

### PR DESCRIPTION
**Pull request by Snuffy2**
## Changes
* Change JuiceboxTelnet from telnetlib to [telnetlib3](https://github.com/jquast/telnetlib3) (Fixes #25)
    * This started the cascade of needing to update every other class to async as well
* Update JuiceboxUDPCUpdater, JuiceboxMQTTHandler (fka. JuiceboxMessageHandler) to async and moved to separate files.
    * In JuiceboxMQTTHandler, built out framework that should better support sending commands from JPP to the JuiceBox as well as storing the latest value sent to HA. Hopefully this, along with the Experimental option below, will facilitate further development of controlling the JuiceBox from JPP/HA.
* Updating PyProxy required essentially a full rewrite so renamed to JuiceboxMITM. Incorporated [asyncio-dgram](https://github.com/jsbronder/asyncio-dgram)
* Add `EXPERIMENTAL` option for users to opt in to the in development functions. Currently this exposes: 
    * `Data from JuiceBox` and `Data from EnelX` sensors to HA
    * A MVP Text field to send "commands" to the JuiceBox
* Improved logging including logging to both stderr and a file. Implement log rotation to keep 14 days of file logs.
* Implemented [aiorun](https://github.com/cjrh/aiorun) and [tini](https://github.com/krallin/tini) for better garbage management, thread cleanup, and graceful shutdowns
* Attempted to incorporate better handling when connections or updates fail. This includes restarting connections, implementing timeouts to prevent freezing, as well as fully exiting the program when too many errors have occurred to allow a docker restart of the app. 
* Incorporate several items from #55 
    * Add ignore remote option, now called `IGNORE_ENELX` option to prevent commands from EnelX to going to the JuiceBox and data from the JuiceBox from going to EnelX
        * Any commands from EnelX will still be captured by JPP
    * Add `Current Rating` sensor
    * Add the parsed fields from the JuiceBox status messages as attributes in the Local Data experimental sensor
* Moving away from `SRC` and `DST` in both the settings and the code as it was not clear what they should contain. 
    * Deprecated the `SRC` option and replaced it with `LOCAL_IP`
    * Deprecated the `DST` option and replaced it with `ENELX_IP`
    * _Current setups using `SRC` and `DST` will continue to work for now but should eventually be updated to the new terms._ 
* Add `LOCAL_PORT` option (Fixes #60)

### CODE REVIEW

**Comment by Snuffy2** [comment]
At this point, I believe this is ready for review and testing. I released it with the `async_beta` docker tag for testing as well.
```
services:
  juicepassproxy:
    image: ghcr.io/snicker/juicepassproxy:async_beta

   [...]
```

I'll likely end up making some more small tweaks and will remove some extraneous logging and commented out code.
@snicker
@ivanfmartinez
@FalconFour

**Comment by ivanfmartinez** [comment]
> At this point, I believe this is ready for review and testing. I released it with the `async_beta` docker tag for testing as well.
> 
> ```
> services:
>   juicepassproxy:
>     image: ghcr.io/snicker/juicepassproxy:async_beta
> 
>    [...]
> ```
> 
> I'll likely end up making some more small tweaks and will remove some extraneous logging and commented out code. @snicker @ivanfmartinez @FalconFour

I will try to test on this weekend.

Thanks

**Comment by ivanfmartinez** [comment]
@Snuffy2 I think that when using ignore_enel_x, the telnet to juicebox step can be skipped

juicepassproxy_tst    | 2024-05-15 09:04:33  INFO      [entrypoint.sh] IGNORE_ENELX: true
juicepassproxy_tst    | 2024-05-15 09:04:33  INFO      [entrypoint.sh] EXPERIMENTAL: true
juicepassproxy_tst    | 2024-05-15 09:04:33  WARNING   [__main__] Starting JuicePass Proxy v0.2.2 (Log Level: INFO)
juicepassproxy_tst    | 2024-05-15 09:04:33  INFO      [__main__] log_loc: /log/juicepassproxy.log
juicepassproxy_tst    | 2024-05-15 09:04:33  INFO      [__main__] config_loc: /config/juicepassproxy.yaml
juicepassproxy_tst    | 2024-05-15 09:04:33  INFO      [__main__] telnet timeout: 30
juicepassproxy_tst    | 2024-05-15 09:05:03  WARNING   [__main__] Error in getting EnelX Server and Port via Telnet. (TimeoutError: Telnet Connection Failed)
juicepassproxy_tst    | 2024-05-15 09:05:03  INFO      [__main__] enelx_server: jbv1.emotorwerks.com
juicepassproxy_tst    | 2024-05-15 09:05:03  INFO      [__main__] enelx_port: 8042
juicepassproxy_tst    | 2024-05-15 09:05:03  INFO      [__main__] local_addr: 172.30.0.2:8042
juicepassproxy_tst    | 2024-05-15 09:05:03  INFO      [__main__] enelx_addr: 158.47.1.128:8042

**Comment by ivanfmartinez** [comment]
When I stopped charging the car, the current value did not change to 0, the proxy just stopped sending updates.

```
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Voltage to 133.0 using hmd/sensor/JuiceBox/Voltage/state
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Energy (Lifetime) to 4117615.0 using hmd/sensor/JuiceBox/Energy--Lifetime-/state
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Status to Charging using hmd/sensor/JuiceBox/Status/state
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Temperature to 69.8 using hmd/sensor/JuiceBox/Temperature/state
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Current Rating to 32.0 using hmd/sensor/JuiceBox/Current-Rating/state
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Frequency to 60.07 using hmd/sensor/JuiceBox/Frequency/state
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Energy (Session) to 1379.0 using hmd/sensor/JuiceBox/Energy--Session-/state
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Current to 12.0 using hmd/sensor/JuiceBox/Current/state
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Power to 1596.0 using hmd/sensor/JuiceBox/Power/state
juicepassproxy_tst    | 2024-05-15 09:42:10  INFO      [ha_mqtt_discoverable.sensors] Setting Data from JuiceBox to X:v09u,s001,F31,u00064112,V1330,L00004117615,S02,T21,M0024,C0024,m0032,t09,i45,e-0001,f6007,r99,b000,B0000000,P0,E0001379,A00120,p0995!ZHS: using hmd/sensor/JuiceBox/Data-from-JuiceBox/state
juicepassproxy_tst    | 2024-05-15 09:42:16  INFO      [ha_mqtt_discoverable.sensors] Setting Voltage to 133.4 using hmd/sensor/JuiceBox/Voltage/state
juicepassproxy_tst    | 2024-05-15 09:42:16  INFO      [ha_mqtt_discoverable.sensors] Setting Energy (Lifetime) to 4117618.0 using hmd/sensor/JuiceBox/Energy--Lifetime-/state
juicepassproxy_tst    | 2024-05-15 09:42:16  INFO      [ha_mqtt_discoverable.sensors] Setting Status to Plugged In using hmd/sensor/JuiceBox/Status/state
juicepassproxy_tst    | 2024-05-15 09:42:16  INFO      [ha_mqtt_discoverable.sensors] Setting Temperature to 69.8 using hmd/sensor/JuiceBox/Temperature/state
juicepassproxy_tst    | 2024-05-15 09:42:16  INFO      [ha_mqtt_discoverable.sensors] Setting Current Rating to 32.0 using hmd/sensor/JuiceBox/Current-Rating/state
juicepassproxy_tst    | 2024-05-15 09:42:16  INFO      [ha_mqtt_discoverable.sensors] Setting Frequency to 60.09 using hmd/sensor/JuiceBox/Frequency/state
juicepassproxy_tst    | 2024-05-15 09:42:16  INFO      [ha_mqtt_discoverable.sensors] Setting Power to 0.0 using hmd/sensor/JuiceBox/Power/state
juicepassproxy_tst    | 2024-05-15 09:42:16  INFO      [ha_mqtt_discoverable.sensors] Setting Data from JuiceBox to X:v09u,s001,F30,u00064118,V1334,L00004117618,S01,T21,M0024,C0024,m0032,t09,i46,e-0001,f6009,r99,b000,B0000000!YM7: using hmd/sensor/JuiceBox/Data-from-JuiceBox/state
juicepassproxy_tst    | 2024-05-15 09:42:17  INFO      [ha_mqtt_discoverable.sensors] Setting Voltage to 205.7 using hmd/sensor/JuiceBox/Voltage/state
juicepassproxy_tst    | 2024-05-15 09:42:17  INFO      [ha_mqtt_discoverable.sensors] Setting Energy (Lifetime) to 4117618.0 using hmd/sensor/JuiceBox/Energy--Lifetime-/state
juicepassproxy_tst    | 2024-05-15 09:42:17  INFO      [ha_mqtt_discoverable.sensors] Setting Status to Unplugged using hmd/sensor/JuiceBox/Status/state
juicepassproxy_tst    | 2024-05-15 09:42:17  INFO      [ha_mqtt_discoverable.sensors] Setting Temperature to 69.8 using hmd/sensor/JuiceBox/Temperature/state
juicepassproxy_tst    | 2024-05-15 09:42:17  INFO      [ha_mqtt_discoverable.sensors] Setting Current Rating to 32.0 using hmd/sensor/JuiceBox/Current-Rating/state
juicepassproxy_tst    | 2024-05-15 09:42:17  INFO      [ha_mqtt_discoverable.sensors] Setting Frequency to 60.09 using hmd/sensor/JuiceBox/Frequency/state
juicepassproxy_tst    | 2024-05-15 09:42:17  INFO      [ha_mqtt_discoverable.sensors] Setting Power to 0.0 using hmd/sensor/JuiceBox/Power/state
juicepassproxy_tst    | 2024-05-15 09:42:17  INFO      [ha_mqtt_discoverable.sensors] Setting Data from JuiceBox to X:v09u,s001,F10,u00064119,V2057,L00004117618,S00,T21,M0024,C0024,m0032,t09,i47,e-0001,f6009,r99,b000,B0000000!Z79: using hmd/sensor/JuiceBox/Data-from-JuiceBox/state


```

**Comment by Snuffy2** [comment]
Will merge this PR into master.
It can be tested from the `edge` Docker tag until packaged into a release
_For those previously testing with the `async_beta` Docker tag, please switch to `edge`_

**Comment by snicker** [comment]
amazing work @Snuffy2, about to set up 0.3.0 locally!

**Pull request merged**
