### PR TITLE
Change udpc_timeout to telnet_timeout and add to readme

### PR DESCRIPTION
**Pull request by Snuffy2**
### Additionally
* Add `telnet_timeout` to the other JuiceboxTelnet calls (`get_enelx_server_port` and `get_juicebox_id`)
* Set the default for `telnet_timeout` to 30 seconds
* Add to readme

### CODE REVIEW

**Comment by Snuffy2** [comment]
@j358 & @snicker please let me know your thoughts on the revision.

**Comment by j358** [comment]
This commit doesn't run for me.
`juicepassproxy  | Traceback (most recent call last):`
`juicepassproxy  |   File "/juicepassproxy/juicepassproxy.py", line 743, in <module>`
`juicepassproxy  |     main()`
`juicepassproxy  |   File "/juicepassproxy/juicepassproxy.py", line 726, in main`
`juicepassproxy  |     udpc_updater = JuiceboxUDPCUpdater(`
`juicepassproxy  |                    ^^^^^^^^^^^^^^^^^^^^`
`juicepassproxy  | TypeError: JuiceboxUDPCUpdater.__init__() got multiple values for argument 'juicebox_host'`

Somehow all of the arguments have been shifted along one when calling JuiceboxUDPCUpdater.
Simple fix would be remove named arguments:
`        udpc_updater = JuiceboxUDPCUpdater(`
`            args.juicebox_host,`
`            jpp_host,`
`            address[1],`
`            telnet_timeout=telnet_timeout,`
`        )`

**Comment by j358** [comment]
Or name all arguments:
Line 726
`        udpc_updater = JuiceboxUDPCUpdater(`
`            juicebox_host=args.juicebox_host,`
`            udpc_host=jpp_host,`
`            udpc_port=address[1],`
`            telnet_timeout=telnet_timeout,`
`        )`

**Comment by Snuffy2** [comment]
Thanks @j358, it looks like I forgot to push my last local commit up. Sorry about that.

**Comment by j358** [comment]
Yep looks good to me

**Pull request merged**
